### ISSUE TITLE
Cannot see the second step of MFA authentication anymore

### ISSUE THREAD

**Issue by virgium03** [IsmaelMartinez/teams-for-linux#1031]
**Describe the bug**
Cannot login anymore after performing a `Quit` with the `Clear Storage` option. I don't know if that's what caused the issue but it worked initially.

**To Reproduce**
While trying to login, when presented with the second step of the MFA authentication, the screen is blank and there is an error in the console.

**Expected behavior**
Should be able to login after performing the MFA steps.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Installation package via the `Ubuntu Software` app
 - Version team-for-linux@1.3.22

**Additional context**
The errors in the console:

node:electron/js2c/renderer_init:2 Unable to load preload script: /snap/teams-for-linux/477/resources/app.asar/app/browser/index.js
node:electron/js2c/renderer_init:2 TypeError: Object.defineProperty called on non-object
    at Function.defineProperty (<anonymous>)
    at /snap/teams-for-linu…owser/index.js:43:9
    at Object.<anonymous> (/snap/teams-for-linu…owser/index.js:79:2)
    at Object.<anonymous> (/snap/teams-for-linu…owser/index.js:94:3)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function.<anonymous> (node:electron/js2c/asar_bundle:2:13327)
    at Function._load (node:electron/js2c/renderer_init:2:4757)

**Comment by IsmaelMartinez** [comment]
sorry to hear. Have you tried the latest version? 1.4.2 or even 1.4.3 (pre-release)

**Comment by NaimadTheOne** [comment]
@virgium03 maybe you could try install teams from deb package. I had problem with snapStore version too.

**Comment by alfonder** [comment]
I experience the same issue with the Flatpak version 1.4.3. When installed via deb-package, then MFA authentication completes successfully.

**Comment by jijojosephk** [comment]
Something to do with `sandboxing` then, when native packages work. I tried with `flatpak` and no issues for me.

`flatpak version`: `1.14.4`
`teams-for-linux version`: `1.4.6`

`snap`s have been very problematic for quite a while. Some issues are really harder to fix with `snap`s

**Comment by jijojosephk** [comment]
Closing due to inactivity.
