### ISSUE TITLE
Freezed on the starting splash screen

### ISSUE THREAD

**Issue by aferngas** [IsmaelMartinez/teams-for-linux#1138]
**Describe the bug**
The client remains freezed on the Teams splash screen with header title "loading".

**To Reproduce**
1. Start the app
2. Fill-up your account credentials
3. Click on login

**Screenshots**
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/20236851/a4fccf12-9f3c-4624-a865-7ea466bbd7d8)

**Desktop (please complete the following information):**
 - Fedora 38
 - rpm
 - 1.4.13

**Additional context**
Developer tools console reports the following errors:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/20236851/61fced52-6698-4711-baae-198b456e519e)
> Error: [$parse:syntax] http://errors.angularjs.org/1.5.15/$parse/syntax?p0=%7D&p1=not%20a%20primary%20expression&p2=18&p3=%7B%20panel%3A%20%7Btype%3A%20%20%7D%7D&p4=%7D%7D
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:2:413
    at t.throwError (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:226:427)
    at t.primary (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:223:389)
    at t.unary (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:222:411)
    at t.multiplicative (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:222:157)
    at t.additive (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:221:493)
    at t.relational (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:221:328)
    at t.equality (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:221:153)
    at t.logicalAND (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:221:6)
    at t.logicalOR (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:220:385) <div class="ts-loading" analytics-panel="{{::$root.trackConstants.PanelRegion.main}}" analytics-panel-view="{ panel: {type: {{::$root.trackConstants.panelType.loadingApplication}} }}">

> Uncaught (in promise) DOMException: Failed to get a ServiceWorkerRegistration: The document is in an invalid state.

Developer tools network reports a API call which is not being performed:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/20236851/557edfa9-eaea-41e4-bbb7-95b23c66bb11)
> https://teams.microsoft.com/statics/hashed/precompiled-shared-worker-27a7049206e1cba1.js

**Comment by jijojosephk** [comment]
Is it after the update? can you remove the config folder and start over?

**Comment by aferngas** [comment]
> Is it after the update? can you remove the config folder and start over?

Great! Now works for me!
