### ISSUE TITLE
Not able to build using Nodejs 12

### ISSUE THREAD

**Issue by julian-alarcon** [IsmaelMartinez/teams-for-linux#123]
**Describe the bug**
Trying to build using nodejs 12 shows an error and stop the build

**To Reproduce**
1. Install nodejs 12
2. Try to build the app `yarn install`
3. See error

```
julian@mypc:~/Code/teams-for-linux$ yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⡀ spellchecker
error /home/julian/Code/teams-for-linux/node_modules/spellchecker: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/julian/Code/teams-for-linux/node_modules/spellchecker
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@12.1.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [
gyp info spawn args   '/snap/node/2051/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/julian/Code/teams-for-linux/node_modules/spellchecker/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/snap/node/2051/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/julian/.node-gyp/12.1.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/julian/.node-gyp/12.1.0',
gyp info spawn args   '-Dnode_gyp_dir=/snap/node/2051/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/julian/.node-gyp/12.1.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/julian/Code/teams-for-linux/node_modules/spellchecker',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/julian/Code/teams-for-linux/node_modules/spellchecker/build'
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affentry.o
In file included from ../vendor/hunspell/src/hunspell/affentry.cxx:9:0:
../vendor/hunspell/src/hunspell/affentry.hxx:30:105: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
   struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                         ^~~~
../vendor/hunspell/src/hunspell/affentry.hxx:93:114: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
   struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                                  ^~~~
../vendor/hunspell/src/hunspell/affentry.cxx: In member function ‘int PfxEntry::test_condition(const char*)’:
../vendor/hunspell/src/hunspell/affentry.cxx:113:20: warning: this statement may fall through [-Wimplicit-fallthrough=]
          case '.': if (!pos) { // dots are not metacharacters in groups: [.]
                    ^~
../vendor/hunspell/src/hunspell/affentry.cxx:120:5: note: here
     default: {
     ^~~~~~~
../vendor/hunspell/src/hunspell/affentry.cxx: In member function ‘int SfxEntry::test_condition(const char*, const char*)’:
../vendor/hunspell/src/hunspell/affentry.cxx:501:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
         case '.': if (!pos) { // dots are not metacharacters in groups: [.]
                   ^~
../vendor/hunspell/src/hunspell/affentry.cxx:516:5: note: here
     default: {
     ^~~~~~~
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/affixmgr.o
In file included from ../vendor/hunspell/src/hunspell/affixmgr.cxx:12:0:
../vendor/hunspell/src/hunspell/affentry.hxx:30:105: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
   struct hentry *      check_twosfx(const char * word, int len, char in_compound, const FLAG needflag = NULL);
                                                                                                         ^~~~
../vendor/hunspell/src/hunspell/affentry.hxx:93:114: warning: converting to non-pointer type ‘short unsigned int’ from NULL [-Wconversion-null]
   struct hentry *   check_twosfx(const char * word, int len, int optflags, PfxEntry* ppfx, const FLAG needflag = NULL);
                                                                                                                  ^~~~
../vendor/hunspell/src/hunspell/affixmgr.cxx: In member function ‘int AffixMgr::parse_convtable(char*, FileMgr*, RepList**, const char*)’:
../vendor/hunspell/src/hunspell/affixmgr.cxx:3654:64: warning: argument to ‘sizeof’ in ‘int strncmp(const char*, const char*, size_t)’ call is the same expression as the second source; did you mean to provide an explicit length? [-Wsizeof-pointer-memaccess]
                              if (strncmp(piece, keyword, sizeof(keyword)) != 0) {
                                                                ^
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/csutil.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/dictmgr.o
../vendor/hunspell/src/hunspell/dictmgr.cxx: In member function ‘int DictMgr::parse_file(const char*, const char*)’:
../vendor/hunspell/src/hunspell/dictmgr.cxx:102:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
                        pdict->region=NULL;
                                     ^
../vendor/hunspell/src/hunspell/dictmgr.cxx:103:21: note: here
                     case 2: //deliberate fallthrough
                     ^~~~
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/filemgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hashmgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hunspell.o
../vendor/hunspell/src/hunspell/hunspell.cxx: In member function ‘int Hunspell::spell(const char*, int*, char**)’:
../vendor/hunspell/src/hunspell/hunspell.cxx:369:19: warning: this statement may fall through [-Wimplicit-fallthrough=]
             *info += SPELL_ORIGCAP;
../vendor/hunspell/src/hunspell/hunspell.cxx:370:6: note: here
      case NOCAP: {
      ^~~~
../vendor/hunspell/src/hunspell/hunspell.cxx:439:13: warning: this statement may fall through [-Wimplicit-fallthrough=]
             }
             ^
../vendor/hunspell/src/hunspell/hunspell.cxx:441:6: note: here
      case INITCAP: {
      ^~~~
../vendor/hunspell/src/hunspell/hunspell.cxx: In member function ‘int Hunspell::suggest(char***, const char*)’:
../vendor/hunspell/src/hunspell/hunspell.cxx:741:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
                     capwords = 1;
                     ~~~~~~~~~^~~
../vendor/hunspell/src/hunspell/hunspell.cxx:742:6: note: here
      case HUHCAP: {
      ^~~~
../vendor/hunspell/src/hunspell/hunspell.cxx:865:24: warning: this statement may fall through [-Wimplicit-fallthrough=]
               capwords = 1;
               ~~~~~~~~~^~~
../vendor/hunspell/src/hunspell/hunspell.cxx:866:11: note: here
           case HUHCAP: {
           ^~~~
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/hunzip.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/phonet.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/replist.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/hunspell/suggestmgr.o
  CXX(target) Release/obj.target/hunspell/vendor/hunspell/src/parsers/textparser.o
  AR(target) Release/obj.target/hunspell.a
  COPY Release/hunspell.a
  CXX(target) Release/obj.target/spellchecker/src/main.o
../src/main.cc:195:20: error: ‘Handle’ has not been declared
   static void Init(Handle<Object> exports) {
                    ^~~~~~
../src/main.cc:195:26: error: expected ‘,’ or ‘...’ before ‘<’ token
   static void Init(Handle<Object> exports) {
                          ^
../src/main.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Spellchecker::CheckSpelling(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cc:61:5: error: ‘Handle’ was not declared in this scope
     Handle<String> string = Handle<String>::Cast(info[0]);
     ^~~~~~
../src/main.cc:61:5: note: suggested alternative: ‘handle’
     Handle<String> string = Handle<String>::Cast(info[0]);
     ^~~~~~
     handle
../src/main.cc:61:18: error: expected primary-expression before ‘>’ token
     Handle<String> string = Handle<String>::Cast(info[0]);
                  ^
../src/main.cc:61:20: error: ‘string’ was not declared in this scope
     Handle<String> string = Handle<String>::Cast(info[0]);
                    ^~~~~~
../src/main.cc:61:20: note: suggested alternatives:
In file included from /usr/include/c++/7/iosfwd:39:0,
                 from /usr/include/c++/7/memory:72,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:21,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/usr/include/c++/7/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
/usr/include/c++/7/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
../src/main.cc:61:42: error: expected primary-expression before ‘>’ token
     Handle<String> string = Handle<String>::Cast(info[0]);
                                          ^
../src/main.cc:61:45: error: ‘::Cast’ has not been declared
     Handle<String> string = Handle<String>::Cast(info[0]);
                                             ^~~~
../src/main.cc:85:89: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       misspelled_range->Set(Nan::New("start").ToLocalChecked(), Nan::New<Integer>(start));
                                                                                         ^
In file included from /home/julian/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:25,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/home/julian/.node-gyp/12.1.0/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/julian/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cc:86:85: warning: ‘bool v8::Object::Set(v8::Local<v8::Value>, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       misspelled_range->Set(Nan::New("end").ToLocalChecked(), Nan::New<Integer>(end));
                                                                                     ^
In file included from /home/julian/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:25,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/home/julian/.node-gyp/12.1.0/include/node/v8.h:3359:26: note: declared here
                     bool Set(Local<Value> key, Local<Value> value));
                          ^
/home/julian/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cc:87:42: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       result->Set(index, misspelled_range);
                                          ^
In file included from /home/julian/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:25,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/home/julian/.node-gyp/12.1.0/include/node/v8.h:3368:26: note: declared here
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/julian/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Spellchecker::CheckSpellingAsync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cc:97:5: error: ‘Handle’ was not declared in this scope
     Handle<String> string = Handle<String>::Cast(info[0]);
     ^~~~~~
../src/main.cc:97:5: note: suggested alternative: ‘handle’
     Handle<String> string = Handle<String>::Cast(info[0]);
     ^~~~~~
     handle
../src/main.cc:97:18: error: expected primary-expression before ‘>’ token
     Handle<String> string = Handle<String>::Cast(info[0]);
                  ^
../src/main.cc:97:20: error: ‘string’ was not declared in this scope
     Handle<String> string = Handle<String>::Cast(info[0]);
                    ^~~~~~
../src/main.cc:97:20: note: suggested alternatives:
In file included from /usr/include/c++/7/iosfwd:39:0,
                 from /usr/include/c++/7/memory:72,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:21,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/usr/include/c++/7/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
   typedef basic_string<char>    string;
                                 ^~~~~~
/usr/include/c++/7/bits/stringfwd.h:74:33: note:   ‘std::__cxx11::string’
../src/main.cc:97:42: error: expected primary-expression before ‘>’ token
     Handle<String> string = Handle<String>::Cast(info[0]);
                                          ^
../src/main.cc:97:45: error: ‘::Cast’ has not been declared
     Handle<String> string = Handle<String>::Cast(info[0]);
                                             ^~~~
../src/main.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Spellchecker::GetAvailableDictionaries(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cc:156:73: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       result->Set(i, Nan::New(dict.data(), dict.size()).ToLocalChecked());
                                                                         ^
In file included from /home/julian/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:25,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/home/julian/.node-gyp/12.1.0/include/node/v8.h:3368:26: note: declared here
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/julian/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE {anonymous}::Spellchecker::GetCorrectionsForMisspelling(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/main.cc:179:42: warning: ‘bool v8::Object::Set(uint32_t, v8::Local<v8::Value>)’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       result->Set(i, val.ToLocalChecked());
                                          ^
In file included from /home/julian/.node-gyp/12.1.0/include/node/v8-internal.h:14:0,
                 from /home/julian/.node-gyp/12.1.0/include/node/v8.h:25,
                 from /home/julian/.node-gyp/12.1.0/include/node/node.h:63,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/home/julian/.node-gyp/12.1.0/include/node/v8.h:3368:26: note: declared here
                     bool Set(uint32_t index, Local<Value> value));
                          ^
/home/julian/.node-gyp/12.1.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/main.cc: In static member function ‘static void {anonymous}::Spellchecker::Init(int)’:
../src/main.cc:210:5: error: ‘exports’ was not declared in this scope
     exports->Set(Nan::New("Spellchecker").ToLocalChecked(), tpl->GetFunction());
     ^~~~~~~
../src/main.cc:210:78: error: no matching function for call to ‘v8::FunctionTemplate::GetFunction()’
     exports->Set(Nan::New("Spellchecker").ToLocalChecked(), tpl->GetFunction());
                                                                              ^
In file included from /home/julian/.node-gyp/12.1.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:53,
                 from ../src/main.cc:3:
/home/julian/.node-gyp/12.1.0/include/node/v8.h:5947:46: note: candidate: v8::MaybeLocal<v8::Function> v8::FunctionTemplate::GetFunction(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
                                              ^~~~~~~~~~~
/home/julian/.node-gyp/12.1.0/include/node/v8.h:5947:46: note:   candidate expects 1 argument, 0 provided
../src/main.cc: At global scope:
../src/main.cc:214:11: error: variable or field ‘Init’ declared void
 void Init(Handle<Object> exports, Handle<Object> module) {
           ^~~~~~
../src/main.cc:214:11: error: ‘Handle’ was not declared in this scope
../src/main.cc:214:11: note: suggested alternative: ‘rand_r’
 void Init(Handle<Object> exports, Handle<Object> module) {
           ^~~~~~
           rand_r
../src/main.cc:214:24: error: expected primary-expression before ‘>’ token
 void Init(Handle<Object> exports, Handle<Object> module) {
                        ^
../src/main.cc:214:26: error: ‘exports’ was not declared in this scope
 void Init(Handle<Object> exports, Handle<Object> module) {
                          ^~~~~~~
../src/main.cc:214:35: error: ‘Handle’ was not declared in this scope
 void Init(Handle<Object> exports, Handle<Object> module) {
                                   ^~~~~~
../src/main.cc:214:35: note: suggested alternative: ‘rand_r’
 void Init(Handle<Object> exports, Handle<Object> module) {
                                   ^~~~~~
                                   rand_r
../src/main.cc:214:48: error: expected primary-expression before ‘>’ token
 void Init(Handle<Object> exports, Handle<Object> module) {
                                                ^
../src/main.cc:214:50: error: ‘module’ was not declared in this scope
 void Init(Handle<Object> exports, Handle<Object> module) {
                                                  ^~~~~~
../src/main.cc:214:50: note: suggested alternative: ‘mode_t’
 void Init(Handle<Object> exports, Handle<Object> module) {
                                                  ^~~~~~
                                                  mode_t
In file included from ../../nan/nan.h:53:0,
                 from ../src/main.cc:3:
../src/main.cc:220:27: error: ‘Init’ was not declared in this scope
 NODE_MODULE(spellchecker, Init)
                           ^
/home/julian/.node-gyp/12.1.0/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/main.cc:220:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(spellchecker, Init)
 ^~~~~~~~~~~
../src/main.cc:220:27: note: suggested alternative:
 NODE_MODULE(spellchecker, Init)
                           ^
/home/julian/.node-gyp/12.1.0/include/node/node.h:556:36: note: in definition of macro ‘NODE_MODULE_X’
       (node::addon_register_func) (regfunc),                          \
                                    ^~~~~~~
../src/main.cc:220:1: note: in expansion of macro ‘NODE_MODULE’
 NODE_MODULE(spellchecker, Init)
 ^~~~~~~~~~~
/home/julian/.node-gyp/12.1.0/include/node/node.h:217:18: note:   ‘node::Init’
 NODE_EXTERN void Init(int* argc,
                  ^~~~
spellchecker.target.mk:120: recipe for target 'Release/obj.target/spellchecker/src/main.o' failed
make: Leaving directory '/home/julian/Code/teams-for-linux/node_modules/spellchecker/build'
make: *** [Release/obj.target/spellchecker/src/main.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/snap/node/2051/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.18.0-18-generic
gyp ERR! command "/snap/node/2051/bin/node" "/snap/node/2051/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/julian/Code/teams-for-linux/node_modules/spellchecker
gyp ERR! node -v v12.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Expected behavior**
Build should work

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 0.2.1

**Additional context**

**Comment by julian-alarcon** [comment]
Seems related to this https://github.com/atom/node-spellchecker/issues/112

**Comment by IsmaelMartinez** [comment]
Yeah, I link it in the low  quality issue as a newer version of chrome might solve that problem. Unfortunately, that breaks the spellchecker and the other module that we are using. Not sure if we can call it a bug as its not really a bug in our app. It does block us from been able to move to electron 5.

**Comment by IsmaelMartinez** [comment]
I did remove the "bug" label as might be misleading.

We will need also to contribute in here for the update... or create a fork from that project an integrate the spellchecker fix.
https://github.com/mixmaxhq/electron-spell-check-provider

**Comment by Thalvik** [comment]
+1 I can confirm this also

**Comment by IsmaelMartinez** [comment]
I have removed the need to use electron-spell-check-provider so maybe git it another try?
