### ISSUE TITLE
Maximising Window causes application to close on PopOS 22.04 

### ISSUE THREAD

**Issue by Gundalf72** [IsmaelMartinez/teams-for-linux#1233]
Maximising the Teams window causes the application to quit.

**To Reproduce**
1. Open Teams 
2. Click on maximise

- or - 
1. Drag teams to screen edge (where it docks and maximises

**Expected behavior**
Teams window is full screen.

**Desktop (please complete the following information):**
 - OS: PopOS 22.04
 - Installation flatpack
 - Version [e.g. 1.4.30

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/5445345/2305d008-a626-4366-9aca-2644f51188b5)

**Additional context**
I have 2 machines. The other one runs 1.4.29 and doesn't have the problem.

**Comment by jijojosephk** [comment]
launch from terminal `flatpak run com.github.IsmaelMartinez.teams_for_linux --appLogLevels=error,warn,info,deb` and post the logs here.

**Comment by Gundalf72** [comment]
`andrew@xxxx:~$ flatpak run com.github.IsmaelMartinez.teams_for_linux --appLogLevels=error,warn,info,deb
[2:0429/101655.710376:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[WARN] No config file found, using default values
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 10:16:55.931: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:16:55.932: Failed to load module "canberra-gtk-module"
[2:0429/101655.950615:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/101655.950667:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/101656.065124:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/101656.065177:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/101656.065198:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[ERROR] Failed to fetch custom background remote configuration. net::ERR_CONNECTION_REFUSED
[2:0429/101656.725267:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
`

**Comment by jijojosephk** [comment]
I wonder why I don't see `INFO` and `DEBUG` messages. Are you sure you passed all values for log?

**Comment by jijojosephk** [comment]
Sorry it's `--appLogLevels=error,warn,info,debug`

**Comment by Gundalf72** [comment]
andrew@xxxxxx:~$ flatpak run com.github.IsmaelMartinez.teams_for_linux --appLogLevels=error,warn,info,debug
[2:0429/121835.632584:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[DEBUG] configPath:,/home/andrew/.var/app/com.github.IsmaelMartinez.teams_for_linux/config/teams-for-linux
[WARN] No config file found, using default values
[DEBUG] configFile:,[object Object]
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 12:18:35.868: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:18:35.869: Failed to load module "canberra-gtk-module"
[2:0429/121835.888310:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/121835.888342:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[DEBUG] Fetching custom background configuration from 'http://localhost/config.json'
[DEBUG] Custom background service url is 'http://localhost'
[DEBUG] processArgs:,/app/teams-for-linux/teams-for-linux,--appLogLevels=error,warn,info,debug
[2:0429/121836.004322:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/121836.004363:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0429/121836.004426:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[DEBUG] Testing network using net.request() for https://teams.microsoft.com/
[DEBUG] Spellchecker is disabled!
[ERROR] Failed to fetch custom background remote configuration. net::ERR_CONNECTION_REFUSED
[DEBUG] Network test successful with method https
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 1s, IdleState: 'active'
[2:0429/121837.093857:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] did-frame-finish-load,[object Object],true
[DEBUG] did-finish-load
[DEBUG] Badge count set to '0'
[DEBUG] Badge count set to '0'
[DEBUG] Badge count set to '0'
[DEBUG] did-frame-finish-load,[object Object],false
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
....

The app quits immediately without logging anything else.

Thanks!

**Comment by jijojosephk** [comment]
I assume you're not on new alpha COSMIC RUST.

**Comment by jijojosephk** [comment]
We never faced such issue.

**Comment by Gundalf72** [comment]
No, nothing fancy or cutting edge.

It looks the same as this one on Debian / KDE https://github.com/IsmaelMartinez/teams-for-linux/issues/1236 that's just been added.

**Comment by jijojosephk** [comment]
No problem in `GNOME` any other `electron` based app behaving the same way?

**Comment by jijojosephk** [comment]
Wonder why there is no logs from `chromium/electron`.

**Comment by Gundalf72** [comment]
Hi @jijojosephk, the log is verbose but this looks promising. 

It's about 1/2 through the log, before I try to resize the window

[2:0430/132900.718122:INFO:CONSOLE(43)] "Uncaught (in promise) #<Object>", source: https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/main-97f7c6514d40a559.js (43)
[2:0430/132900.799208:INFO:CONSOLE(14)] "title changed", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/mutationTitle.js (14)
[2:0430/132900.799250:INFO:CONSOLE(15)] "General (Zenith Working Groups) | Microsoft Teams classic", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/mutationTitle.js (15)
[2:0430/132900.799312:INFO:CONSOLE(19)] "0", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/mutationTitle.js (19)
[2:0430/132900.816228:INFO:CONSOLE(14)] "title changed", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/mutationTitle.js (14)
[2:0430/132900.816322:INFO:CONSOLE(15)] "Microsoft Teams classic", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/mutationTitle.js (15)
[2:0430/132900.816387:INFO:CONSOLE(19)] "0", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/mutationTitle.js (19)
[2:0430/132900.844267:INFO:CONSOLE(16)] "sending tray-update", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/trayIconRenderer.js (16)
[2:0430/132900.847342:INFO:CONSOLE(16)] "sending tray-update", source: /app/teams-for-linux/resources/app.asar/app/browser/tools/trayIconRenderer.js (16)
[2:0430/132900.882235:INFO:CONSOLE(114)] "TypeError: Cannot read properties of null (reading 'resizeObserver')
    at https://statics.teams.cdn.office.net/hashed/3.2-app.min-961da7a.js:1:12335238
    at b.$broadcast (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:145:391)
    at b.$destroy (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:141:367)
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:272:302
    at m.$digest (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:140:365)
    at v.$digest (https://statics.teams.cdn.office.net/hashed/3.2-app.min-961da7a.js:1:6069377)
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:143:82
    at e (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:42:305)
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js:45:222 undefined", source: https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-14969ec.js (114)
[2:0430/132901.526190:INFO:CONSOLE(1)] "message handler already registered for - pulsarSignal", source: https://statics.teams.cdn.office.net/teams-modular-packages/hashed-assets/299585-fbbd0a47af487590.js (1)

**Comment by IsmaelMartinez** [comment]
can you check if starting the app with the following flag solves your crash? `--useMutationTitleLogic=false` 

It might be the case that because you are still in teamsv1 this new logic is making the app crash. That was the only change in 1.4.30

**Comment by Gundalf72** [comment]
I had been using v2 until this version. Before raising the ticket I used the close + clear cache option that put me back to v1.

Adding the flag didn't work on either.  First I tried it with Teams v1, then I opted in to Teams v2 (via Switch now), closed Teams and re-opened to persiste using v2 going forward.

**Comment by jijojosephk** [comment]
Are you using `config.json`, if so, can you share the contents of the file?

**Comment by jijojosephk** [comment]
This is probably with `electron` upgrade but works fine on `GNOME`,`XFCE` etc. This is going to cause some headache. :smile:

**Comment by jijojosephk** [comment]
I'll try Pop! in VM

**Comment by jijojosephk** [comment]
I believe the problem is with `electron` version `^30`. We can revert to `29.3.0`
