### ISSUE TITLE
1.11.4 regression: t4l dies at startup

### ISSUE THREAD

**Issue by harridu** [IsmaelMartinez/teams-for-linux#1472]
**Describe the bug**
Since the upgrade to version 1.11.4 teams-for-linux dies at startup:
```
{hdunkel@dpcl082:aixigo 09:41:51 (master) 1103} teams-for-linux --trace-warnings --webDebug --logConfig='{}'
all good with appLogLevels you aren't using them
all good with onlineCheckMethod you aren't using them
Initialising logger with config: "{}"
09:41:58.649  File logging at /home/hdunkel/.config/teams-for-linux/logs/main.log with level silly
09:41:58.651  Console logging enabled with level silly
09:41:58.652  Logger initialised
09:41:58.653  configPath: /home/hdunkel/.config/teams-for-linux
09:41:58.653  configFile: { appIcon: '/usr/share/icons/hicolor/48x48/apps/teams-for-linux.png' }
09:41:58.840  (node:324415) UnhandledPromiseRejectionWarning: ReferenceError: config is not defined
    at BrowserWindowManager.createNewBrowserWindow (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/browserWindowManager.js:56:20)
    at BrowserWindowManager.createWindow (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/browserWindowManager.js:31:28)
    at Object.onAppReady (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:43:38)
    at App.handleAppReady (/opt/teams-for-linux/resources/app.asar/app/index.js:246:16)
    at App.emit (node:events:531:35)
    at emitUnhandledRejectionWarning (node:internal/process/promises:298:15)
    at warnWithErrorCodeUnhandledRejectionsMode (node:internal/process/promises:406:5)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
09:41:58.841  (node:324415) ReferenceError: config is not defined
    at BrowserWindowManager.createNewBrowserWindow (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/browserWindowManager.js:56:20)
    at BrowserWindowManager.createWindow (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/browserWindowManager.js:31:28)
    at Object.onAppReady (/opt/teams-for-linux/resources/app.asar/app/mainAppWindow/index.js:43:38)
    at App.handleAppReady (/opt/teams-for-linux/resources/app.asar/app/index.js:246:16)
    at App.emit (node:events:531:35)
[324517:1110/094158.893056:ERROR:viz_main_impl.cc(181)] Exiting GPU process due to errors during initialization
```
After moving back to 1.11.3 the problem is gone.

Verified on Debian 12 and Sid.

**Desktop (please complete the following information):**
 - Debian 12
 - Installation package deb
 - 1.11.4

**Comment by harridu** [comment]
Since it mentions a GPU process: Graphics is NVIDIA's proprietary driver version 535.216.01. The test on Debian 12 was run in a VNC session.

**Comment by IsmaelMartinez** [comment]
1.11.4 is bugged (I forgot a "this" in front of the "config.frame"). As it is a pre-release I am going to kill it and create it again. Apologies for the noise and issue.

**Comment by IsmaelMartinez** [comment]
Can you try again? I have just re-released 1.11.4. thanks

**Comment by harridu** [comment]
The new version works. Thank you very much.

I don't want to complain, and I highly appreciate your work, but for future fixes I would recommend to not re-use a version number.

**Comment by IsmaelMartinez** [comment]
I normally don't reuse version numbers, and definitely not in final
releases. The only case I allow an exception is when is a pre release and
the app is just broken.

Fyi, the frame window should be back in version 1.11.5 as I mistakenly left
if with false and default. I really need some holidays.

If you want the frame back, you can start the app with --frame=true

**Comment by IsmaelMartinez** [comment]
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.11.5 is now ready. Thanks again for reporting the broken 1.11.4.
