### ISSUE TITLE
Not working (blank page)

### ISSUE THREAD

**Issue by vladrusu** [IsmaelMartinez/teams-for-linux#1509]
Using Linux Mint 23 here.
When starting the app, after the login window, all I get is a blank window. Using debug, I noticed these errors:

```precompiled-web-worker-58c87b3e874c25d6.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - peopleProfileService is missing in discover response
    at c (precompiled-web-worker-58c87b3e874c25d6.js:1:1784022)
    at precompiled-web-worker-58c87b3e874c25d6.js:1:6046533
precompiled-web-worker-58c87b3e874c25d6.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - presenceUPS is missing in discover response
    at c (precompiled-web-worker-58c87b3e874c25d6.js:1:1784022)
    at precompiled-web-worker-58c87b3e874c25d6.js:1:6046533
precompiled-web-worker-58c87b3e874c25d6.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - teamsAndChannelsProvisioningService is missing in discover response
    at c (precompiled-web-worker-58c87b3e874c25d6.js:1:1784022)
    at precompiled-web-worker-58c87b3e874c25d6.js:1:6046533
precompiled-web-worker-58c87b3e874c25d6.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - iC3LocationService is missing in discover response
    at c (precompiled-web-worker-58c87b3e874c25d6.js:1:1784022)
    at precompiled-web-worker-58c87b3e874c25d6.js:1:6046533
precompiled-web-worker-58c87b3e874c25d6.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - appsSuggestionService is missing in discover response
    at c (precompiled-web-worker-58c87b3e874c25d6.js:1:1784022)
    at precompiled-web-worker-58c87b3e874c25d6.js:1:6046533
5precompiled-web-worker-58c87b3e874c25d6.js:1 Uncaught (in promise) Error: Discover::regionGtm::InvalidResponse - iC3LocationService is missing in discover response
    at c (precompiled-web-worker-58c87b3e874c25d6.js:1:1784022)
    at precompiled-web-worker-58c87b3e874c25d6.js:1:6046533
VM209:1 message handler already registered for - pulsarSignal
warn @ VM209:1
VM209:1 {}
error @ VM209:1
16The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
12Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.
manifest.json:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
v2/:1 [Deprecation] The keyword 'slider-vertical' specified to an 'appearance' property is not standardized. It will be removed in the future. Use <input type=range style="writing-mode: vertical-lr; direction: rtl"> instead.
VM209:1 Failed to override MS Method
error @ VM209:1
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/customBackgrounds.js:14
setTimeout
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:29
sleep @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:29
whenReady @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:11
whenReady @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:12
VM209:1 Failed to start Activity Hub by assigning Event Handlers
error @ VM209:1
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/activityHub.js:28
setTimeout
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:29
sleep @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:29
whenReady @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:11
whenReady @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:12
VM209:1 Failed to set Default Title
error @ VM209:1
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/activityHub.js:36
setTimeout
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:29
sleep @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:29
whenReady @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:11
whenReady @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/instance.js:12
VM209:1 Failed to set Machine State```

**Comment by IsmaelMartinez** [comment]
Hello,

Can you use the template ? Otherwise there are far too many variables to
consider to be able to help.

Thanks

**Comment by vladrusu** [comment]
Hello,
Version:

teams-for-linux@1.12.3
node:20.18.1
v8: 13.0.2.45.19-electron.0
eectron: 33.2.1
chrome: 130.0.6723.137

installed as .deb package, Linux Mint 23.
![Screenshot from 2024-12-04 09-30-18](https://github.com/user-attachments/assets/0d1acdf4-3451-4a1f-b65f-f1ebfccf500a)


Running as command line:
`vlad@vlad-home:~$ teams-for-linux --webDebug --logConfig='{}'`

```
No config file found, using default values
all good with appLogLevels you aren't using them
Initialising logger with config: "{}"
09:26:39.148 › File logging at /home/vlad/.config/teams-for-linux/logs/main.log with level silly
09:26:39.149 › Console logging enabled with level silly
09:26:39.150 › Logger initialised
09:26:39.150 › configPath: /home/vlad/.config/teams-for-linux
09:26:39.150 › configFile: {}
09:26:39.289 › processArgs: [
  '/opt/teams-for-linux/teams-for-linux',
  '--webDebug',
  '--logConfig={}'
]
09:26:39.290 › testing RegExp processArgs false
09:26:39.290 › testing RegExp processArgs false
09:26:39.290 › testing RegExp processArgs false
09:26:39.291 › Waiting for network...
09:26:39.291 › Testing network using net.request() for https://teams.microsoft.com
09:26:39.292 › Spellchecker is disabled!
09:26:39.461 › Network test successful with method https
09:26:39.736 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[16496:1204/092639.741306:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
09:26:40.219 › did-frame-finish-load {} true
09:26:40.220 › did-finish-load
09:26:42.638 › Badge count set to '0'
09:26:42.893 › did-frame-finish-load {} false
09:26:43.008 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
09:26:43.213 › did-frame-finish-load {} true
09:26:43.213 › did-finish-load
09:26:44.050 › Badge count set to '0'
09:26:44.273 › did-frame-finish-load {} false
09:26:53.064 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
```

I also attach a screenshot (via debug option).

**Comment by javaes** [comment]
Hi @vladrusu, I've encountered the same issue not only when using this electron wrapper of the Web UI but also when using MS Teams Web UI in Firefox and Chromium.

After switching my Browser's User-Agent to a Windows browser I could successfully launch the Web UI in my browser and properly login. After that I was able to switch it back to Linux and the page kept working, so there are clearly some issues on MS Teams side.

**Comment by IsmaelMartinez** [comment]
Hi @vladrusu , can you try removing your config folder? More info in https://github.com/IsmaelMartinez/teams-for-linux/blob/main/KNOWN_ISSUES.md#config-folder-locations , but do check if you have the same problem as @javaes , as it might just be a Microsoft issue or you having a non supported version of Chromium
