### ISSUE TITLE
Hangs at initializing, eventually fails.

### ISSUE THREAD

**Issue by JoeyG1973** [IsmaelMartinez/teams-for-linux#188]
This is the only error I see in debug.  Everything works in chrome.  Running Fedora 29 with rpm teams-for-linux-0.3.0-362.x86_64.  This all worked yesterday.  See the image for what it shows when it eventually bombs.  I tried signing out and signing back in as the failure page suggested.

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.
_:367 index.html: register for events
_:373 index.html: check for appcache update. State: 2
_:383 index.html: update not ready, continue with app start
_:440 index.html: unregister all service workers
_:1 Document was loaded from Application Cache with manifest https://teams.microsoft.com/skypespaces.appcache
_:1 Application Cache Checking event
_:1 Application Cache NoUpdate event
2-vendor.min-42f06dbd.js:195 JQMIGRATE: Migrate is installed, version 3.0.1
DevTools failed to parse SourceMap: https://statics.teams.microsoft.com/hashedjs/2-vendor.min.js-0a6e1420.map
_:356 index.html: remove startup cache listeners
_:1160 Loading stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.theme-default.min-3b5fcafa.css
_:1181 Loaded stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.theme-default.min-3b5fcafa.css
3.2-app.min-69f6ec5b.js:1 SettingsService: Refreshing settings. 
[Array(1)]
3.2-app.min-69f6ec5b.js:1 SettingsService: Refreshing settings. 
[Array(1)]
angular.min.js:35 Uncaught IPC object is null
angular.min.js:112 Error: Action with name notificationsService_startup already exists
    at r.registerAction (https://statics.teams.microsoft.com/hashedjs/3.1-app.min-29433e23.js:2004:5774)
    at new n (https://statics.teams.microsoft.com/hashedjs/4-app.desktop.min-2c8b7c16.js:9:1263)
    at Object.instantiate (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:491)
    at Object.<anonymous> (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:38:260)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at Object.$get (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:35:71)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:39:175
    at d (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:36:369)
    at e (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:96) undefined
The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.
_:1 The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.
DevTools failed to parse SourceMap: https://statics.teams.microsoft.com/hashedjs/3.2-app.min.js-aac7feca.map
3.2-app.min-69f6ec5b.js:3 Cleaned the join location

![image](https://user-images.githubusercontent.com/10002637/62159321-68f74f00-b2df-11e9-88c1-c09710b57e0f.png)

**Comment by IsmaelMartinez** [comment]
Hi,

Can you use the template when reporting possible bugs? https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md

This eases tackling them.

Also, have you check the KNOWN_ISSUES section? It does smell like this https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page.

Closing until more info is provided and the template is used for reporting the issue.
