### ISSUE TITLE
App does not start

### ISSUE THREAD

**Issue by mschop** [IsmaelMartinez/teams-for-linux#202]
**Describe the bug**
The app does not start correctly. It shows a blank screen. In the app bar stands "Microsoft Teams - Initialisierung läuft". "Initialisierung läuft" is German for "Initialisation runs".

In the Debug Console, the following error is thrown:

```
Error: Action with name notificationsService_startup already exists
    at r.registerAction (https://statics.teams.microsoft.com/hashedjs/3.1-app.min-47228058.js:2008:5774)
    at new n (https://statics.teams.microsoft.com/hashedjs/4-app.desktop.min-b52e7579.js:9:1263)
    at Object.instantiate (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:491)
    at Object.<anonymous> (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:38:260)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at Object.$get (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:35:71)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:39:175
    at d (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:36:369)
    at e (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:96) undefined
```

The same behaviour applies to snap installation and manual run (git clone + yarn start).

**To Reproduce**
1. Start Teams for Linux

**Expected behavior**
Teams should start normal.

**Screenshots**
![bug-teams-for-linux](https://user-images.githubusercontent.com/8030310/62605119-bd12bc80-b8f9-11e9-9743-471b0c9a702e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - snap / source
 - Teams for linux version 0.4.0 and 0.5.0

**Comment by IsmaelMartinez** [comment]
This is a known issue that unfortunately happens at random. Some people are more affected than others. Info about how to deal with it is in here: https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page

**Comment by IsmaelMartinez** [comment]
duplicated by #171

**Comment by mschop** [comment]
@IsmaelMartinez

The directories listed in your link didn't exist on my system. There was a `~/.config/teams-for-linux/Partitions`. But there was no `teams-4-linux`. There was only a `teams`-directory. But in this directory, there was no `Service Worker`directory.

I even completely removed the directory `~/.config/teams-for-linux`. But even that didn't help.

The only thing that helped, was to remove the snap package and reinstall it.

So now it is working for me.

Thanks very much!

**Comment by IsmaelMartinez** [comment]
Hi @mschop , check the thread. Snap stores the config in another folder (I can't look for it at the moment but is in the #171 thread)

**Comment by mschop** [comment]
@IsmaelMartinez thx!!!

**Comment by joschaharpeng1337** [comment]
@IsmaelMartinez thx. The app is now working again. Your app makes teams usable for me - thanks again.
