### ISSUE TITLE
Stuck on "Microsoft Teams - Initializing..."

### ISSUE THREAD

**Issue by xire28** [IsmaelMartinez/teams-for-linux#211]
**Describe the bug**
```
Uncaught IPC object is null
_:349 index.html: cache up-to-date
_:356 index.html: remove startup cache listeners
0-angular-jquery.min-8200dd6f.js:113 Error: Action with name notificationsService_startup already exists
    at r.registerAction (https://statics.teams.microsoft.com/hashedjs/3.1-app.min-47228058.js:2008:5774)
    at new n (https://statics.teams.microsoft.com/hashedjs/4-app.desktop.min-b52e7579.js:9:1263)
    at Object.instantiate (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:491)
    at Object.<anonymous> (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:38:260)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at Object.$get (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:35:71)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:39:175
    at d (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:36:369)
    at e (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:96) undefined
(anonymous) @ 0-angular-jquery.min-8200dd6f.js:113
The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

_#/conversations/19:2fd84904-90e9-47ba-9393-c4d12191f077_56a07a3a-cdf8-4372-b106-6d3494d2c79b@unq.gbl.spaces?ctx=chat:1 The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

3.2-app.min-041c173e.js:3 Cleaned the join location

```

**To Reproduce**
Start the application

**Expected behavior**
Application to start correctly

**Desktop (please complete the following information):**
 - Debian GNU/Linux 9 (stretch) 64-bit (gnome 3.22.2)
 - deb
 - 0.6.0 (amd64)

**Additional context**
Try to upgrade to 0.6.0 to fix this issue but it's still present

**Comment by xire28** [comment]
duplicates of #171
