### ISSUE TITLE
`CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by simonsteiner1984** [IsmaelMartinez/teams-for-linux#223]
0.6.6 has this error, 0.1.12 is working ok:

/opt/teams-for-linux/resources/electron.asar/renderer/init.js:159 Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /tmp/.org.chromium.Chromium.H7F3ZZ)

There is
https://github.com/electron-userland/electron-builder/issues/2958

**Comment by simonsteiner1984** [comment]
No

**Comment by IsmaelMartinez** [comment]
Probably best to try to revert to electron builder 20.24.4 (the one from version 0.4.0). Like that we bypass this issue and #208

**Comment by IsmaelMartinez** [comment]
Just increased the version to 21.2.0 in https://github.com/IsmaelMartinez/teams-for-linux/pull/231 

I think this fixes this issue also.

**Comment by IsmaelMartinez** [comment]
I just done a pre-release in here so you can test it.
https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.6.7

Once confirmed, I will start preparing the proper release docs, etc.

**Comment by simonsteiner1984** [comment]
I get the same error

**Comment by simonsteiner1984** [comment]
I also get
Uncaught IPC object is null
angular.min.js:112 Error: Action with name notificationsService_startup already exists
    at r.registerAction (https://statics.teams.microsoft.com/hashedjs/3.1-app.min-c183a110.js:2019:5777)
    at new n (https://statics.teams.microsoft.com/hashedjs/4-app.desktop.min-cb39f420.js:9:1263)
    at Object.instantiate (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:491)
    at Object.<anonymous> (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:38:260)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at Object.$get (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:35:71)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:39:175
    at d (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:36:369)
    at e (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:96) undefined

**Comment by simonsteiner1984** [comment]
/tmp/.mount_teams-nG8maL/resources/electron.asar/renderer/init.js:158 Unable to load preload script: /tmp/.mount_teams-nG8maL/resources/app.asar/app/browser/index.js
(anonymous) @ /tmp/.mount_teams-nG8maL/resources/electron.asar/renderer/init.js:158

**Comment by simonsteiner1984** [comment]
I clean ~/.config/teams-for-linux and first login works, 2nd time i open the app it doesnt work

**Comment by IsmaelMartinez** [comment]
What version are you using?

**Comment by simonsteiner1984** [comment]
0.6.7

**Comment by IsmaelMartinez** [comment]
Can you describe, one by one, the steps to reproduce the error? The IPC is
#171 and the as fixed in 0.6.6.

**Comment by simonsteiner1984** [comment]
delete ~/.config/teams-for-linux, start app login, close app, open app, you get a white screen

**Comment by IsmaelMartinez** [comment]
Also, not to be a pest but best open a but using the bug template. It will
safe us lots of time.

**Comment by IsmaelMartinez** [comment]
marking this as invalid as not even reading this 3 times I can understand the basics of your issue. 

Can you use a bug template and provide as much information as possible? It toes help to fix the issue. The blank/white screen is #171 and it should be fixed for version 0.6.6. Make sure you are deleting the right electron config folder, it does depend on your packaging system.
