### ISSUE TITLE
After refresh teams doesnot load

### ISSUE THREAD

**Issue by Ankit895** [IsmaelMartinez/teams-for-linux#228]
angular.min.js:112 Error: Action with name notificationsService_startup already exists
    at r.registerAction (https://statics.teams.microsoft.com/hashedjs/3.1-app.min-c183a110.js:2019:5777)
    at new n (https://statics.teams.microsoft.com/hashedjs/4-app.desktop.min-cb39f420.js:9:1263)
    at Object.instantiate (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:491)
    at Object.<anonymous> (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:38:260)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at Object.$get (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:35:71)
    at Object.invoke (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:390)
    at https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:39:175
    at d (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:36:369)
    at e (https://statics.teams.microsoft.com/hashedjs/0-angular-jquery.min-8200dd6f.js:37:96) undefined

**Comment by IsmaelMartinez** [comment]
Please refer to #171 

https://github.com/IsmaelMartinez/teams-for-linux/issues/171#issuecomment-521149919
