### ISSUE TITLE
0.7.0 JavaScript error

### ISSUE THREAD

**Issue by stephen-gowing** [IsmaelMartinez/teams-for-linux#239]
# Fix

This is now fixed in all releases. Apologies again and thanks to @jef79m for the PR. Without it, I will be still preparing the fix release.

for anyone using snap, the following command should fix this issue:

`sudo snap refresh teams-for-linux` 

Clean your application cache before starting:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page

If you still get a blank screen, clean your config location:
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#config-folder-locations

If you still have a blank screen, please report it in #171 and I can reopen that issue.

# Original message

Removed all previous versions & cleared the config directories, installed from RPM. The client is running, but no windows pop up and it doesn't appear in the icon tray anymore. Running CentOS 7.6, GNOME 3.28.2.

```
sbg@tegan:~ >/opt/teams-for-linux/teams-for-linux
A JavaScript error occurred in the main process
Uncaught Exception:
/opt/teams-for-linux/resources/app.asar/app/config/index.js:91
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
[...]
```

```
sbg@tegan:~ >pgrep -al teams-for-linux
22754 /opt/teams-for-linux/teams-for-linux
22762 /opt/teams-for-linux/teams-for-linux --type=zygote --no-sandbox
22846 /opt/teams-for-linux/teams-for-linux --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox --gpu-preferences=KAAAAAAAAACAAABAAQAAAAAAAAAAAGAAAAAAAAAAAAAIAAAAAAAAAAgAAAAAAAAA --service-request-channel-token=16849459641371971947
```

Seeing the same behaviour in the AppImage:

```
sbg@tegan:~ >Downloads/teams-for-linux-0.7.0.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
/tmp/.mount_teams-zWmaft/resources/app.asar/app/config/index.js:91
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by drohm** [comment]
I'm getting same error on Ubuntu Budgie 19.04:

```
A JavaScript error occurred in the main process
Uncaught Exception:
/opt/teams-for-linux/resources/app.asar/app/config/index.js:91
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
```

**Comment by karthick-kk** [comment]
I'm getting the same error on Kubuntu 19.04 (with .deb and appimage)

A JavaScript error occurred in the main process
Uncaught Exception:
/opt/teams-for-linux/resources/app.asar/app/config/index.js:91
<<<<<<< HEAD
^^

SyntaxError: Unexpected token <<
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:660:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by jroigfer** [comment]
I'm geeting the same error on Ubuntu 18.04 using snap.

**Comment by IsmaelMartinez** [comment]
Apologies, merge issue. I did the release in a bit of a rush and now is paying back. A build is happening as I write, once that is done I will push that to master. Apologies again

**Comment by hetii** [comment]
The same here on Ubuntu-mate 19.04.
Btw if it's issue just in teams-for-linux maybe there should be multiple version available in download section. So people can install and test older one?

Regards.

**Comment by IsmaelMartinez** [comment]
You can find any older versions in the release folder of this repo.

**Comment by IsmaelMartinez** [comment]
Released to snapd and moved the release in here as pre-release unti I manage to get up the bed properly. snap refresh should do the job. Apologies. You only learn from mistakes and I will definitely change the CD/CI process.

**Comment by IsmaelMartinez** [comment]
Please confirm fixes the issue. I will add more extra checks as, currently, it's only me the check... And on Sunday before going to bed is never safe time to release...

**Comment by karibe** [comment]
Nope, now I have:
Error org.freedesktop.DBus.Error.Failed: cannot use setting "default-url-scheme-handler": not allowed
I'm not sure if it's related but hangs on: Microsoft Teams - initializing...

**Comment by IsmaelMartinez** [comment]
Did you clear the config folder? The "error" is actually only a snap warning. The blank screen is #171 . Check the known issues section for info about the config folder location

**Comment by karibe** [comment]
OK, works after doing https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/KNOWN_ISSUES.md#blank-page

**Comment by IsmaelMartinez** [comment]
You should only need to do this once. Otherwise #171 fix doesn't really work

**Comment by IsmaelMartinez** [comment]
This is now fixed in all releases. Apologies again and thanks to @jef79m for the PR. Without it, I will be still preparing the fix release.

**Comment by jroigfer** [comment]
Solved!!!
