### ISSUE TITLE
Cannot share screen nor window with snap

### ISSUE THREAD

**Issue by crazyscientist** [IsmaelMartinez/teams-for-linux#505]
I have been using the snap in the past successfully. For a while I was using the official client, but yesterday I switched back.

**Describe the bug**

It seems somewhere along the road screen sharing got broken. 

I cannot share a screen or window. Once it fails to share something I cannot reactive the camera.

**To Reproduce**
1. Start a meeting
2. Activate camera (if not done automatically)
3. Open the dialog for screen sharing
4. Select a screen or window (does not matter which one) to share
4. Camera gets disabled by Teams
5. Problem: Screen/window is not shared
6. Problem: When going back to step 3, step 4 does not offer a choice which screen/window to share
7. Problem: Clicking on the Camera button does not re-enable the camera

**Expected behavior**

* The chosen screen/window gets shared
* Sharing can be stopped
* Camera can be reactivated

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Installation package: snap
 - Version 1.0.17
 - Revision 205

also:

- Version 1.0.20
- Revision 211

**Additional context**

In debug mode with version 1.0.20 I get get following errors, when opening the dialog for screen sharing:

```
2021-11-25T09:16:58.638Z [screenSharing][control] screenSharingControlService: unexpected, cannot find the call, teamsCallId [1]
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:114
e.logMessage	@	3.2-app.min-7eb358a.js:1
e.error	@	3.2-app.min-7eb358a.js:1
e.getSharingCall	@	3.1-app.min-423881d.js:1
e.setSharingSource	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
pI	@	3.1-app.min-423881d.js:1
e.startScreenSharingOnCall	@	3.1-app.min-423881d.js:1
r.startSharing	@	3.1-app.min-423881d.js:1
a.startSharing	@	3.1-app.min-423881d.js:1
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:246
b	@	0.2-angular-jquery.min-eee9041.js:122
e	@	0.2-angular-jquery.min-eee9041.js:270
$eval	@	0.2-angular-jquery.min-eee9041.js:142
$apply	@	0.2-angular-jquery.min-eee9041.js:142
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:270
dispatch	@	0.2-angular-jquery.min-eee9041.js:1
v.handle	@	0.2-angular-jquery.min-eee9041.js:1

---

TypeError: Cannot read properties of undefined (reading 'send')
    at a.startSharing (https://statics.teams.cdn.office.net/hashed/3.1-app.min-423881d.js:1:6056590)
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:246:461
    at b (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:122:133)
    at e (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:270:195)
    at m.$eval (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:142:180)
    at m.$apply (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:142:413)
    at HTMLDivElement.<anonymous> (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:270:247)
    at HTMLDivElement.dispatch (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:1:41506)
    at HTMLDivElement.v.handle (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:1:39536) undefined
	(anonymous)	@	0.2-angular-jquery.min-eee9041.js:114
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:85
(anonymous)	@	3.1-app.min-423881d.js:1
$apply	@	0.2-angular-jquery.min-eee9041.js:142
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:270
dispatch	@	0.2-angular-jquery.min-eee9041.js:1
v.handle	@	0.2-angular-jquery.min-eee9041.js:1
```

Once clicking on a screen to share I get the following error messages:

```
TypeError: Cannot read properties of undefined (reading 'width')
    at startStreaming (/snap/teams-for-linux/211/resources/app.asar/app/browser/desktopShare/chromeApi.js:27:41)
    at EventEmitter.<anonymous> (/snap/teams-for-linux/211/resources/app.asar/app/browser/desktopShare/chromeApi.js:13:4)
    at Object.onceWrapper (node:events:514:26)
    at EventEmitter.emit (node:events:394:28)
    at Object.onMessage (node:electron/js2c/renderer_init:81:1017) undefined
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:114
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:85
(anonymous)	@	3.1-app.min-423881d.js:1
t.onerror	@	3.2-app.min-7eb358a.js:1
error (async)		
(anonymous)	@	3.2-app.min-7eb358a.js:1
invoke	@	0.2-angular-jquery.min-eee9041.js:37
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:39
q	@	0.2-angular-jquery.min-eee9041.js:3
bb	@	0.2-angular-jquery.min-eee9041.js:39
c	@	0.2-angular-jquery.min-eee9041.js:17
yc	@	0.2-angular-jquery.min-eee9041.js:17
e.bootstrap	@	1-vendor.min-a609edf.js:1
e	@	_:23
dispatch	@	0.2-angular-jquery.min-eee9041.js:1
v.handle	@	0.2-angular-jquery.min-eee9041.js:1
load (async)		
add	@	0.2-angular-jquery.min-eee9041.js:1
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:1
each	@	0.2-angular-jquery.min-eee9041.js:1
each	@	0.2-angular-jquery.min-eee9041.js:1
Se	@	0.2-angular-jquery.min-eee9041.js:1
on	@	0.2-angular-jquery.min-eee9041.js:1
(anonymous)	@	1-vendor.min-a609edf.js:1
(anonymous)	@	1-vendor.min-a609edf.js:1

---

Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at startStreaming (/snap/teams-for-linu…are/chromeApi.js:27)
    at EventEmitter.<anonymous> (/snap/teams-for-linu…are/chromeApi.js:13)
    at Object.onceWrapper (node:events:514)
    at EventEmitter.emit (node:events:394)
    at Object.onMessage (node:electron/js2c/renderer_init:81)
startStreaming	@	/snap/teams-for-linu…are/chromeApi.js:27
(anonymous)	@	/snap/teams-for-linu…are/chromeApi.js:13
onceWrapper	@	node:events:514
emit	@	node:events:394
onMessage	@	node:electron/js2c/renderer_init:81
```

When I try to reopen the dialog I get these error messages:

```
2021-11-25T09:23:22.830Z [screenSharing][control] screenSharingControlService: unexpected, cannot find the call, teamsCallId [1]
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:114
e.logMessage	@	3.2-app.min-7eb358a.js:1
e.error	@	3.2-app.min-7eb358a.js:1
e.getSharingCall	@	3.1-app.min-423881d.js:1
e.setSharingSource	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
pI	@	3.1-app.min-423881d.js:1
e.startScreenSharingOnCall	@	3.1-app.min-423881d.js:1
r.startSharing	@	3.1-app.min-423881d.js:1
a.startSharing	@	3.1-app.min-423881d.js:1
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:246
b	@	0.2-angular-jquery.min-eee9041.js:122
e	@	0.2-angular-jquery.min-eee9041.js:270
$eval	@	0.2-angular-jquery.min-eee9041.js:142
$apply	@	0.2-angular-jquery.min-eee9041.js:142
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:270
dispatch	@	0.2-angular-jquery.min-eee9041.js:1
v.handle	@	0.2-angular-jquery.min-eee9041.js:1

---

TypeError: Cannot read properties of undefined (reading 'send')
    at a.startSharing (https://statics.teams.cdn.office.net/hashed/3.1-app.min-423881d.js:1:6056590)
    at https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:246:461
    at b (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:122:133)
    at e (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:270:195)
    at m.$eval (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:142:180)
    at m.$apply (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:142:413)
    at HTMLDivElement.<anonymous> (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:270:247)
    at HTMLDivElement.dispatch (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:1:41506)
    at HTMLDivElement.v.handle (https://statics.teams.cdn.office.net/hashed/0.2-angular-jquery.min-eee9041.js:1:39536) undefined
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:114
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:85
(anonymous)	@	3.1-app.min-423881d.js:1
$apply	@	0.2-angular-jquery.min-eee9041.js:142
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:270
dispatch	@	0.2-angular-jquery.min-eee9041.js:1
v.handle	@	0.2-angular-jquery.min-eee9041.js:1

**Comment by micwoj92** [comment]
Are you using wayland?

**Comment by crazyscientist** [comment]
Sorry, forgot to mention that. I'm running X11.

**Comment by jijojosephk** [comment]
@crazyscientist , Could you answer the questions below?

- Are you using desktop or laptop?
- Do you have multiple display setup?
- What's the resolution of the primary display?
- What options do you see for 'Quality' in the screen sharing preview?

**Comment by crazyscientist** [comment]
@jijojosephk Sure, no problem...

* Laptop: Dell Precision 5530
* Multiple Display setup: yes (via USB-C docking station)
```
$ xrandr
Screen 0: minimum 320 x 200, current 7040 x 1440, maximum 16384 x 16384
eDP-1 connected 1920x1080+5120+0 (normal left inverted right x axis y axis) 344mm x 194mm
   1920x1080     60.00*+  59.97    59.96    59.93
[...]
DP-1 connected primary 5120x1440+0+0 (normal left inverted right x axis y axis) 1200mm x 340mm
   5120x1440     59.98*+  29.98
[...]
```
* Primary screen resolution: 5120x1440
* Visible options for Quality: None

Maybe this might also be a helpful information: After closing the dialog I get this error in the JS console:

```
callingAgents: calling-stack [JS.TsCalling.MediaAgent] ffffffff: MA/DeviceManager/MediaStreamManager [940e263c] Error from promiseQueue! {"type":"MediaStreamRequestError","detail":"media stream request error: Access denied constraints: {\"audio\":null,\"video\":{\"maxWidth\":1920,\"minWidth\":1920,\"maxHeight\":1080,\"minHeight\":1080,\"fps\":15,\"deviceId\":\"u30\"},\"withTimeout\":false,\"withEffect\":false}","isAudio":false,"message":"media stream request error: Access denied constraints: {\"audio\":null,\"video\":{\"maxWidth\":1920,\"minWidth\":1920,\"maxHeight\":1080,\"minHeight\":1080,\"fps\":15,\"deviceId\":\"u30\"},\"withTimeout\":false,\"withEffect\":false}"}
	(anonymous)	@	0.2-angular-jquery.min-eee9041.js:114
e.logMessage	@	3.2-app.min-7eb358a.js:1
e.error	@	3.2-app.min-7eb358a.js:1
e.apply	@	3.1-app.min-423881d.js:1
e.error	@	3.1-app.min-423881d.js:1
t.log	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	rt-js-bindings.bundle-db8ace5.js:1
t.log	@	rt-js-bindings.bundle-db8ace5.js:1
e.error	@	rt-js-bindings.bundle-db8ace5.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
e._apply	@	skype-calling-plugin…bundle-a41a268.js:1
e.error	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
Promise.catch (async)		
e.add	@	skype-calling-plugin…bundle-a41a268.js:1
e.getStream	@	skype-calling-plugin…bundle-a41a268.js:1
t.getOrCreateMediaStream	@	skype-calling-plugin…bundle-a41a268.js:1
t.startStream	@	skype-calling-plugin…bundle-a41a268.js:1
t.start	@	skype-calling-plugin…bundle-a41a268.js:1
t.start	@	skype-calling-plugin…bundle-a41a268.js:1
t.getMediaStream	@	skype-calling-plugin…bundle-a41a268.js:1
t.getMediaStream	@	skype-calling-plugin…bundle-a41a268.js:1
t.createDevicesHandle	@	skype-calling-plugin…bundle-a41a268.js:1
n.getScreenHandle	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
i	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
c	@	skype-calling-plugin…bundle-a41a268.js:1
n.startScreenSharing	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
i	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
a	@	skype-calling-plugin…bundle-a41a268.js:1
Promise.then (async)		
c	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
r	@	skype-calling-plugin…bundle-a41a268.js:1
t.executeInternal	@	skype-calling-plugin…bundle-a41a268.js:1
t.checkPendingOperationAndExecute	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
i	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
(anonymous)	@	skype-calling-plugin…bundle-a41a268.js:1
r	@	skype-calling-plugin…bundle-a41a268.js:1
t.execute	@	skype-calling-plugin…bundle-a41a268.js:1
N	@	skype-calling-plugin…bundle-a41a268.js:1
h.value	@	skype-calling-plugin…bundle-a41a268.js:1
l	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
o	@	3.1-app.min-423881d.js:1
Promise.then (async)		
l	@	3.1-app.min-423881d.js:1
(anonymous)	@	3.1-app.min-423881d.js:1
pI	@	3.1-app.min-423881d.js:1
e.startScreenSharingOnCall	@	3.1-app.min-423881d.js:1
r.startSharing	@	3.1-app.min-423881d.js:1
a.startSharing	@	3.1-app.min-423881d.js:1
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:246
b	@	0.2-angular-jquery.min-eee9041.js:122
e	@	0.2-angular-jquery.min-eee9041.js:270
$eval	@	0.2-angular-jquery.min-eee9041.js:142
$apply	@	0.2-angular-jquery.min-eee9041.js:142
(anonymous)	@	0.2-angular-jquery.min-eee9041.js:270
dispatch	@	0.2-angular-jquery.min-eee9041.js:1
v.handle	@	0.2-angular-jquery.min-eee9041.js:1
```

**Comment by jijojosephk** [comment]
@crazyscientist I understood the problem. There is a logic which filters quality of video entries based on the primary display resolution. I would disable that logic and it should work for you. Thanks for reporting.
