### ISSUE TITLE
Upgrade electron version to 20.0.0

### ISSUE THREAD

**Issue by jijojosephk** [IsmaelMartinez/teams-for-linux#542]
**Describe the bug**
It's a build activity not a bug. This would upgrade all the dependencies.

**To Reproduce**
1. Not applicable.

**Expected behavior**
Not applicable.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Installation package: [All]
 - Electron version: 20.0.0
 - Node version: 16.16.0

**Additional context**

**Comment by jijojosephk** [comment]
![image](https://user-images.githubusercontent.com/11662148/182317880-57bdbdfd-06db-4725-8184-5294727c072a.png)

Spellchecker is dead! Sorry, I'll have to remove it.

**Comment by jijojosephk** [comment]
@IsmaelMartinez snap publish fails. Something wrong with credentials.

`Run yarn dist:linux:snap --publish always
yarn run v1.22.19
$ electron-builder -l snap --publish always
  • electron-builder  version=23.3.3 os=5.15.0-101[4](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:5)-azure
  • loaded configuration  file=package.json ("build" field)
  • packaging       platform=linux arch=x64 electron=20.0.0 appOutDir=dist/linux-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v20.0.0/electron-v20.0.0-linux-x64.zip size=89 MB parts=4
  • downloaded      url=https://github.com/electron/electron/releases/download/v20.0.0/electron-v20.0.0-linux-x64.zip duration=2[5](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:6)5ms
  • building        target=snap arch=x[6](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:7)4 file=dist/teams-for-linux_1.0.25_amd64.snap
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.[7](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:8)z size=1.5 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-4.0-2/snap-template-electron-4.0-2-amd64.tar.7z duration=100ms
  • downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z size=1.6 MB parts=1
  • downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-12.0.1/appimage-12.0.1.7z duration=6[8](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:9)ms
  • publishing      publisher=Snap Store
  • uploading       file=teams-for-linux_1.0.25_amd64.snap provider=snapStore
Provided credentials are no longer valid for the Snap Store.                   
Recommended resolution: Regenerate them and try again.                         
Full execution log: '/home/runner/.cache/snapcraft/log/snapcraft-20220802-0[9](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:10)1547.568133.log'                                                                   
  ⨯ exit status 1
github.com/develar/app-builder/pkg/util.ExecuteAndPipeStdOutAndStdErr
	/Volumes/data/Documents/app-builder/pkg/util/exec.go:23
github.com/develar/app-builder/pkg/package-format/snap.publishToStore
	/Volumes/data/Documents/app-builder/pkg/package-format/snap/snapStore.go:35
github.com/develar/app-builder/pkg/package-format/snap.ConfigurePublishCommand.func1
	/Volumes/data/Documents/app-builder/pkg/package-format/snap/snapStore.go:18
github.com/alecthomas/kingpin.(*actionMixin).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/actions.go:28
github.com/alecthomas/kingpin.(*Application).applyActions
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:557
github.com/alecthomas/kingpin.(*Application).execute
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:390
github.com/alecthomas/kingpin.(*Application).Parse
	/Volumes/data/go/pkg/mod/github.com/alecthomas/kingpin@v2.2.6+incompatible/app.go:222
main.main
	/Volumes/data/Documents/app-builder/main.go:90
runtime.main
	/usr/local/Cellar/go/1.17/libexec/src/runtime/proc.go:255
runtime.goexit
	/usr/local/Cellar/go/1.17/libexec/src/runtime/asm_amd64.s:1581  
  ⨯ /home/runner/work/teams-for-linux/teams-for-linux/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1  failedTask=build stackTrace=Error: /home/runner/work/teams-for-linux/teams-for-linux/node_modules/app-builder-bin/linux/x64/app-builder process failed ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
Exit code:
1
    at ChildProcess.<anonymous> (/home/runner/work/teams-for-linux/teams-for-linux/node_modules/builder-util/src/util.ts:250:14)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:[10](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:11)88:[16](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:17))
    at Process.ChildProcess._handle.onexit (internal/child_process.js:[29](https://github.com/IsmaelMartinez/teams-for-linux/runs/7628293554?check_suite_focus=true#step:6:30)6:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.`

**Comment by jijojosephk** [comment]
Completed upgrade.
