### ISSUE TITLE
Bright flash when starting the app even with dark theme enabled

### ISSUE THREAD

**Issue by sxiii** [IsmaelMartinez/teams-for-linux#636]
**Describe the bug**
When I start the Teams, it starts loading with full white background, which kills eyes. This might probably considered both as a bug and as a feature improvements. The problem should be in one out of three places (or in several places): Teams code itself, Teams-for-Linux and/or Electron. Either way, doesn't matter where the bug is originating, I think this can be fixed with a CSS styling or blocking of showing any content before the app fully loads a page (I would be happy with both approaches).

**To Reproduce**
1. Set up teams-for-linux in dark mode.
2. Fully close teams.
3. Open teams-for-linux.
4. See bright flash with fully white background for 5 seconds (sometimes more) while app loads the resources etc.

**Expected behavior**
Dark theme should be dark at all times.

**Screenshots**
![image](https://user-images.githubusercontent.com/575925/198957846-43ca2564-6bc5-46f6-911a-4a131664ba6d.png)

**Desktop (please complete the following information):**
 - OS: Garuda Linux Soaring Talon Linux rog-strix 6.0.5-arch1-g14-1
 - Installation package: teams-for-linux from AUR: https://aur.archlinux.org/packages/teams-for-linux
 - Version: 1.0.45-1

**Additional context**
First, fully white background appears for about 2 seconds. Second, Microsoft logo appears for about 2 seconds as well, also on fully white background. Ideally make them both black or remove both of them while app loads.

**Comment by IsmaelMartinez** [comment]
Hi @sxiii , 

If you can try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.46 that will be great. It should in theory detect if your OS has dark mode enabled and pick that up. 

It might not work as I don't have a way to test in linux.

**Comment by sxiii** [comment]
Hello @IsmaelMartinez -- thanks for your test. I can report the following:
* White flash did not disappeared, the Micorosft logo still appears on white background and also I think before Microsoft logo there's short time with full white background as well. **However, I think that white flash had shortened - like now it's 50% shorter or so.** Maybe this is just due to I pre-loaded the app before with older version; not fully sure. 
* Teams in AppImage does work but the mentioned above issue with white flash did not fully disappeared,
* Teams in .tar.gz package format throws an "Uncaught Exception":
<details>
  <summary>Uncaught Exception</summary>

```
 JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'nativeTheme')
    at Object.<anonymous> (/home/s/tfl/teams-for-linux-1.0.46/resources/app.asar/app/mainAppWindow/index.js:3:28)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/s/tfl/teams-for-linux-1.0.46/resources/app.asar/app/index.js:41:23)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
[72903:1107/122113.073014:ERROR:vaapi_wrapper.cc(1299)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[72903:1107/122113.073104:ERROR:vaapi_wrapper.cc(1246)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[72903:1107/122113.073132:ERROR:vaapi_wrapper.cc(1299)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[72903:1107/122113.073148:ERROR:vaapi_wrapper.cc(1246)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
^C[s@rog-strix teams-for-linux-1.0.46]$ ./teams-for-linux 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'nativeTheme')
    at Object.<anonymous> (/home/s/tfl/teams-for-linux-1.0.46/resources/app.asar/app/mainAppWindow/index.js:3:28)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
```
</details>

Can't test AUR version as the package maintainer is probably only upgrading when there's newer Release, not a Pre-release. I might do a manual AUR script later and check it out.
Thanks again @IsmaelMartinez

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen
