### ISSUE TITLE
Will not start under Slackware Linux

### ISSUE THREAD

**Issue by slackwhere** [IsmaelMartinez/teams-for-linux#661]
OS: Slackware Linux
Kernel: 5.15.18
teams-for-linux: 1.0.46
installer: tar.gz

I try to execute teams using the following command, it display the errors below and then hangs, I need to issue control-C to regain the terminal. The version from MS (1.5.00.10453) works as does the PWA version in Chrome.

->./teams-for-linux 
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'nativeTheme')
    at Object.<anonymous> (/home/wcuddy/Downloads/teams/teams-for-linux-1.0.46/resources/app.asar/app/mainAppWindow/index.js:3:28)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/wcuddy/Downloads/teams/teams-for-linux-1.0.46/resources/app.asar/app/index.js:41:23)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
[28384:1218/141342.129074:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[28384:1218/141342.129109:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
libva error: /usr/lib64/dri/i965_drv_video.so init failed

**Comment by IsmaelMartinez** [comment]
hi @slackwhere , 1.0.46 did something odd on the build for tar.gz. Can you try with 1.0.45? Files are here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.45

**Comment by slackwhere** [comment]
1.0.45 does work, thank you  :+1: 

The MS Teams Linux desktop version allows me to pop-out chats with individual people to separate windows. This feature does not seem to exist in the Chrome/PWA version. Do you know if that might eventually be supported in this version.

Thanks again for your response and assistance :)

**Comment by IsmaelMartinez** [comment]
not that I am aware, but it will be a great feature. Hopefully one day their PWA version is that good that I can remove this client, but its been many years 1st without a client, then with a client that was actually not that bad for 90% of the people and now going back to the "no client". One day Microsoft will love Linux as much as we all do.

**Comment by IsmaelMartinez** [comment]
Closing due inactivity. Ping to reopen
